[package]
name = "keystone-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
keystone-config = { path = "../config" }
argon2.workspace = true
base64.workspace = true
chrono.workspace = true
jwt-compact.workspace = true
serde.workspace = true
zeroize.workspace = true
thiserror.workspace = true
